### ISSUE TITLE
Error While initiating performance appraisals

### ISSUE THREAD

**Issue by suicidaldream** [sapplica/sentrifugo#244]
Hi Guys, 
I have an HTTP Error 500 when trying to initialize performance appraisals. 
I have enabled debug mode and found this error in the logs, can you help check please

[02-Apr-2018 13:51:48 Europe/Berlin] PHP Warning:  A non-numeric value encountered in C:\xampp\htdocs\Sentrifugo\Zend\View\Helper\Performancegrid.php on line 665
[02-Apr-2018 13:51:49 Europe/Berlin] PHP Warning:  A non-numeric value encountered in C:\xampp\htdocs\Sentrifugo\Zend\View\Helper\Performancegrid.php on line 665
[02-Apr-2018 13:51:55 Europe/Berlin] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\Sentrifugo\application\modules\default\controllers\AppraisalinitController.php on line 1133
[02-Apr-2018 13:51:55 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Zend_Controller_Action_Helper_FlashMessenger::direct(), 0 passed in C:\xampp\htdocs\Sentrifugo\Zend\Controller\Action\HelperBroker.php on line 328 and exactly 1 expected in C:\xampp\htdocs\Sentrifugo\Zend\Controller\Action\Helper\FlashMessenger.php:262
Stack trace:
#0 C:\xampp\htdocs\Sentrifugo\Zend\Controller\Action\HelperBroker.php(328): Zend_Controller_Action_Helper_FlashMessenger->direct()
#1 C:\xampp\htdocs\Sentrifugo\application\modules\default\controllers\AppraisalinitController.php(1187): Zend_Controller_Action_HelperBroker->__call('FlashMessenger', Array)
#2 C:\xampp\htdocs\Sentrifugo\application\modules\default\controllers\AppraisalinitController.php(1635): Default_AppraisalinitController->save(Object(Default_Form_Appraisalinit), 1)
#3 C:\xampp\htdocs\Sentrifugo\Zend\Controller\Action.php(516): Default_AppraisalinitController->editAction()
#4 C:\xampp\htdocs\Sentrifugo\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action->dis in C:\xampp\htdocs\Sentrifugo\Zend\Controller\Action\Helper\FlashMessenger.php on line 262

**Comment by nidhulp** [comment]
Having the same issue but while scheduling interviews:

[14-Dec-2018 10:05:58 Europe/Berlin] PHP Warning:  A non-numeric value encountered in G:\XAMPP\htdocs\sentrifugo\Zend\View\Helper\Grid.php on line 1022
[14-Dec-2018 10:06:47 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Zend_Controller_Action_Helper_FlashMessenger::direct(), 0 passed in G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action\HelperBroker.php on line 328 and exactly 1 expected in G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action\Helper\FlashMessenger.php:262
Stack trace:
#0 G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action\HelperBroker.php(328): Zend_Controller_Action_Helper_FlashMessenger->direct()
#1 G:\XAMPP\htdocs\sentrifugo\application\modules\default\controllers\ScheduleinterviewsController.php(952): Zend_Controller_Action_HelperBroker->__call('FlashMessenger', Array)
#2 G:\XAMPP\htdocs\sentrifugo\application\modules\default\controllers\ScheduleinterviewsController.php(521): Default_ScheduleinterviewsController->save(Object(Default_Form_Interviewrounds), Array)
#3 G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action.php(516): Default_ScheduleinterviewsController->addAction()
#4 G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Dispatcher\Standard.php(295): Zend in G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action\Helper\FlashMessenger.php on line 262
[14-Dec-2018 10:07:52 Europe/Berlin] PHP Warning:  A non-numeric value encountered in G:\XAMPP\htdocs\sentrifugo\Zend\View\Helper\Grid.php on line 1022
[14-Dec-2018 10:08:22 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Zend_Controller_Action_Helper_FlashMessenger::direct(), 0 passed in G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action\HelperBroker.php on line 328 and exactly 1 expected in G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action\Helper\FlashMessenger.php:262
Stack trace:
#0 G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action\HelperBroker.php(328): Zend_Controller_Action_Helper_FlashMessenger->direct()
#1 G:\XAMPP\htdocs\sentrifugo\application\modules\default\controllers\ScheduleinterviewsController.php(952): Zend_Controller_Action_HelperBroker->__call('FlashMessenger', Array)
#2 G:\XAMPP\htdocs\sentrifugo\application\modules\default\controllers\ScheduleinterviewsController.php(521): Default_ScheduleinterviewsController->save(Object(Default_Form_Interviewrounds), Array)
#3 G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action.php(516): Default_ScheduleinterviewsController->addAction()
#4 G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Dispatcher\Standard.php(295): Zend in G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action\Helper\FlashMessenger.php on line 262
[14-Dec-2018 10:09:10 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Zend_Controller_Action_Helper_FlashMessenger::direct(), 0 passed in G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action\HelperBroker.php on line 328 and exactly 1 expected in G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action\Helper\FlashMessenger.php:262
Stack trace:
#0 G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action\HelperBroker.php(328): Zend_Controller_Action_Helper_FlashMessenger->direct()
#1 G:\XAMPP\htdocs\sentrifugo\application\modules\default\controllers\ScheduleinterviewsController.php(731): Zend_Controller_Action_HelperBroker->__call('FlashMessenger', Array)
#2 G:\XAMPP\htdocs\sentrifugo\application\modules\default\controllers\ScheduleinterviewsController.php(521): Default_ScheduleinterviewsController->save(Object(Default_Form_Interviewrounds), Array)
#3 G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action.php(516): Default_ScheduleinterviewsController->addAction()
#4 G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Dispatcher\Standard.php(295): Zend in G:\XAMPP\htdocs\sentrifugo\Zend\Controller\Action\Helper\FlashMessenger.php on line 262
