### ISSUE TITLE
Fatal error: Uncaught TypeError: in_array()

### ISSUE THREAD

**Issue by mjxo** [sapplica/sentrifugo#372]
Hello guys,

I'm having an issue while trying to download pdf, after completed installation.

Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in C:\xampp\htdocs\Sentrifugo_3.2\application\modules\default\library\FPDF\fpdf.php:526 Stack trace: #0 C:\xampp\htdocs\Sentrifugo_3.2\application\modules\default\library\FPDF\fpdf.php(526): in_array('helvetica', NULL) #1 C:\xampp\htdocs\Sentrifugo_3.2\data\generatereport.php(108): FPDF->SetFont('helvetica', '', 12) #2 {main} thrown in C:\xampp\htdocs\Sentrifugo_3.2\application\modules\default\library\FPDF\fpdf.php on line 526

Did anybody experience this issue? What would be the solution?

Thanks in advance.

**Comment by hikmet2000** [comment]
Hi, I'm having the same issue, did you find a solution?

**Comment by dagnebeyene1** [comment]
I am having similar issue pleas help us

**Comment by che-azeh** [comment]
Unbelievable its not been solved after 3 years.

**Comment by maxmilianoBozzalla** [comment]
Is there any news about this problem? I'm experiencing it and I don't know how to solve it.
